version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
      
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - auth-network
      - mysql-network
      
  clients-service:
    build: ./clients-service
    container_name: clients-service
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    ports:
      - "8084:8084"
    networks:
      - clients-network
      - mysql-network
      
  products-service:
    build: ./products-service
    container_name: products-service
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    ports:
      - "8083:8083"
    networks:
      - products-network
      - mysql-network
      - logs-network
      
  sales-service:
    build: ./sales-service
    container_name: sales-service
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    ports:
      - "8085:8085"
    networks:
      - sales-network
      - mysql-network
      - logs-network
           
  logs-service:
    build: ./logs-service
    container_name: logs-service
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    ports:
      - "8086:8086"
    networks:
      - logs-network
      - mysql-network
      
networks:
  mysql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
   
  auth-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
        
  clients-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
      
  products-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
    
  sales-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/16
        
  logs-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/16

volumes:
  mysql_data:
